TypeError: a bytes-like object is required, not 'str' SOLVE
This solves this error : https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in